/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("cz.habarta.typescript-generator.java-conventions")
}

dependencies {
    api(project(":typescript-generator-core"))
    api("org.springframework.boot:spring-boot-starter-web:2.7.3")
    api("org.springframework.data:spring-data-commons:2.7.2")
    testImplementation(project(":typescript-generator-core"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
    testImplementation("io.swagger:swagger-annotations:1.6.9")
    testImplementation("io.swagger.core.v3:swagger-annotations:2.2.7")
}

description = "typescript-generator-spring"
