/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "typescript-generator"
include(":typescript-generator-gradle-plugin")
include(":typescript-generator-core")
//include(":typescript-generator-maven-plugin")
//include(":typescript-generator-spring")
