/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://repo.gradle.org/gradle/libs-releases-local/")
    }
}

group = "org.utoft.typescript-generator"
java {
    toolchain {
        getLanguageVersion().set(JavaLanguageVersion.of(11))
    }
}

publishing {
    repositories {
        maven {
            name = "localPluginRepository"
            url = uri("../local-plugin-repository")
        }
        maven {
            name = "nexus"
            url = uri("https://dc1-nexs004.systematicgroup.local/repository/CURA_3RD_PARTY")
            credentials(PasswordCredentials::class)
        }
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
