/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("cz.habarta.typescript-generator.java-conventions")
}

dependencies {
    api("com.fasterxml.jackson.core:jackson-databind:2.14.1")
    api("com.fasterxml.jackson.module:jackson-module-jakarta-xmlbind-annotations:2.14.1")
    api("com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.14.1")
    api("org.glassfish.jaxb:jaxb-runtime:4.0.1")
    api("javax.xml.bind:jaxb-api:2.3.1")
    api("javax.ws.rs:javax.ws.rs-api:2.1.1")
    api("jakarta.ws.rs:jakarta.ws.rs-api:3.1.0")
    api("io.github.classgraph:classgraph:4.8.149")
    api("com.google.code.gson:gson:2.9.1")
    api("org.jetbrains.kotlin:kotlin-stdlib:1.7.20")
    api("org.jetbrains:annotations:23.0.0")
    api("org.jetbrains.kotlin:kotlin-reflect:1.7.20")
    api("javax.json.bind:javax.json.bind-api:1.0")
    api("jakarta.json.bind:jakarta.json.bind-api:3.0.0")
    api("org.graalvm.js:js-scriptengine:22.2.0")
    api("jakarta.json:jakarta.json-api:2.1.3")
    api("javax.json:javax.json-api:1.1.4")

    runtimeOnly("org.graalvm.js:js:22.2.0")
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
    testImplementation("org.immutables:value:2.9.1")
    testImplementation("com.google.code.findbugs:annotations:3.0.1u2")
    testImplementation("com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.14.1")
    testImplementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.14.1")
    testImplementation("org.glassfish.jersey.containers:jersey-container-jdk-http:3.0.8")
    testImplementation("org.glassfish.jersey.media:jersey-media-json-binding:3.0.8")
    testImplementation("org.glassfish.jersey.media:jersey-media-json-jackson:3.0.8")
    testImplementation("org.glassfish.jersey.inject:jersey-hk2:3.0.8")
    testImplementation("io.swagger:swagger-annotations:1.6.9")
    testImplementation("io.swagger.core.v3:swagger-annotations:2.2.7")
    testImplementation("org.checkerframework:checker-qual:3.25.0")
    testImplementation("com.google.guava:guava:31.1-jre")
    testImplementation("com.fasterxml.jackson.datatype:jackson-datatype-guava:2.14.1")
    testImplementation("joda-time:joda-time:2.12.2")
    testImplementation("com.fasterxml.jackson.datatype:jackson-datatype-joda:2.14.1")
    testImplementation("io.vavr:vavr:0.10.3")
    testImplementation("io.vavr:vavr-jackson:0.10.3")
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

description = "typescript-generator-core"
//
//val testsJar by tasks.registering(Jar::class) {
//    archiveClassifier.set("tests")
//    from(sourceSets["test"].output)
//}

//(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
