/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("java-gradle-plugin")
    id("cz.habarta.typescript-generator.java-conventions")
}


gradlePlugin {
    plugins {
        create("typescriptGeneratorPlugin") {
            id = "org.utoft.typescript-generator"
            implementationClass = "cz.habarta.typescript.generator.gradle.TypeScriptGeneratorPlugin"
        }
    }
}

dependencies {
    api("org.codehaus.groovy:groovy-all:2.4.21")
    compileOnly(gradleApi())
    api(project(":typescript-generator-core"))
//    compileOnly("org.gradle:gradle-core:6.7")
//    compileOnly("org.gradle:gradle-core-api:6.7")
//    compileOnly("org.gradle:gradle-model-core:6.7")
//    compileOnly("org.gradle:gradle-base-services:6.7")
//    compileOnly("org.gradle:gradle-base-services-groovy:6.7")
//    compileOnly("org.gradle:gradle-logging:6.7")
}

description = "typescript-generator-gradle-plugin"
