/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("java-gradle-plugin")
    id("cz.habarta.typescript-generator.java-conventions")
    id("com.gradle.plugin-publish") version "1.0.0"
}

gradlePlugin {
    vcsUrl.set("https://github.com/jutoft/typescript-generator.git")
    plugins {
        create("typescriptGeneratorPlugin") {
            id = "org.utoft.typescript-generator"
            implementationClass = "cz.habarta.typescript.generator.gradle.TypeScriptGeneratorPlugin"
        }
    }
}

dependencies {
    compileOnly(gradleApi())
    api(project(":typescript-generator-core"))
}

description = "typescript-generator-gradle-plugin"
